### PR TITLE
Add a Unicode version of the Beta Code files

### PR DESCRIPTION
**Pull request by normansimonr**
This commit adds a Unicode version of the .CCT files provided by Professor Robinson to Ulrik. The script used to convert the files is also included in this commit. This Unicode version is potentially more accessible than the Beta code one in modern computers and websites. The new files are in Comma-Separated-Values (CSV) format.

For more details, consult the `README` file in the `csv-unicode` folder.

### CODE REVIEW

**Comment by normansimonr** [comment]
@emg Hi Ulrik! Just bumping this in case you didn't get notified! Also let me know if you'd like me to add more documentation to this commit.

**Review by emg — APPROVED** [review]
@normansimonr Well done, Norman! I am so grateful, so impressed with your beautiful work. Thank you so much. I will merge this.

**Comment by emg** [comment]
Norman, you're clearly a pro. Thank you for this beautiful Python code, and for your work. Merging your pull request and closing with gratitude to you.

**Comment by normansimonr** [comment]
Awesome! Thanks to you for allowing me to help!

**Pull request merged**
