### PR TITLE
Fix medial sigma bug, plus additional minor fix

### PR DESCRIPTION
**Pull request by countingpine**
This is an updated version of #6, to fix a minor bug and merge into the master branch after the addition of #11.

Fixes sigmas at the end of square backets being (in some cases) misinterpreted as medials, e.g. https://github.com/byztxt/byzantine-majority-text/blob/f2b96b9c4fe022431e6f2a944e2505a10528ec6b/textonly-beta-code/JUDE.CCT#L7

Where `[u(ma^s]` is misconverted to `[ὑμᾶσ]`.

Also fixes a minor bug introduced in Mark 16:8 where a space before `]]` is removed.

https://github.com/byztxt/byzantine-majority-text/blob/master/csv-unicode/with-variants/MR.csv#L667

### CODE REVIEW

**Comment by normansimonr** [comment]
@countingpine Everything looks good. Great job! I would say we can merge, but of course we need @emg's review as well. 

Before we merge, I suggest you squash all the commits into one to avoid cluttering the commit history. Are you familiar with the `git rebase` command?

**Comment by countingpine** [comment]
Thanks for your kind words.

Yes, I am happy to squash things down a bit.

I just want to make sure I keep @normansimonr's authorship, and I don't know if I want to merge the Black reformat in with behaviour changes.

I think the best thing will be to rebase his two changes and add a commit for my own fix. That will be neater and more linear, and the result should be identical.

**Comment by normansimonr** [comment]
@countingpine Sounds good!

**Comment by countingpine** [comment]
Thanks.  OK, I've force-pushed now.  Same content, simpler history.

**Comment by normansimonr** [comment]
Brilliant. Now we only need @emg's ok and we're good to go.

**Pull request merged**
